import Foundation

/// The notices for everything Notesage bundles, and the reason they ship.
///
/// Not a courtesy. The desktop app gained this in #971; the iOS app did not,
/// which is why #949 stayed open. Most of the licences here require the notice
/// to travel with the distributed copy, and a shipped `.ipa` is a copy:
///
/// - **MIT / BSD / ISC** — the copyright and permission notice must be
///   included in all copies.
/// - **Apache 2.0** — §4(a) requires giving recipients the licence, §4(d) that
///   the attribution notices be reproduced.
/// - **SIL OFL** — each copy of a bundled face must carry its licence.
///
/// The texts are the projects' own, verbatim, as generated by
/// `scripts/generate-licenses.mjs` into `src/generated/third-party-licenses.json`
/// — not summarised, because a summary is not the notice the licences ask for.
///
/// UIKit-free on purpose, like `LibraryOrdering.swift`: the decoding, the
/// search and the sectioning are the parts that are wrong in ways a screenshot
/// does not show, and `scripts/check-license-catalog.sh` exercises them on
/// macOS. The screen that displays this lives in `LicensesScreen.swift`.
public enum LicenseCatalog {
  /// One dependency, as the generator describes it.
  public struct Component: Decodable, Equatable {
    /// `npm`, `cargo`, or `bundled` — the three the generator emits.
    public let kind: String
    public let name: String
    public let version: String?
    /// SPDX expression where the package declares one.
    public let license: String?
    public let publisher: String?
    public let url: String?
    /// Key into `texts`. Absent when no licence file was found on disk, which
    /// is a packaging fault worth showing rather than hiding — see
    /// `componentsWithoutText`.
    public let textId: String?

    public init(
      kind: String, name: String, version: String? = nil, license: String? = nil,
      publisher: String? = nil, url: String? = nil, textId: String? = nil
    ) {
      self.kind = kind
      self.name = name
      self.version = version
      self.license = license
      self.publisher = publisher
      self.url = url
      self.textId = textId
    }
  }

  /// The generated file: every component, plus the deduplicated notice texts
  /// they point at. Deduplicated because 1,510 components share 395 notices —
  /// carrying them per-component would multiply the payload roughly fourfold.
  public struct Catalog: Decodable, Equatable {
    public let components: [Component]
    public let texts: [String: String]

    public init(components: [Component], texts: [String: String]) {
      self.components = components
      self.texts = texts
    }

    /// The notice for a component, or nil when the generator found no licence
    /// file. Nil is surfaced in the UI rather than skipped: a missing notice is
    /// an obligation unmet, and silence is how it would stay unmet.
    public func text(for component: Component) -> String? {
      guard let id = component.textId else { return nil }
      return texts[id]
    }
  }

  /// A heading in the list, and the components under it.
  public struct Section: Equatable {
    public let title: String
    public let components: [Component]
  }

  /// Decode the generated catalog.
  public static func decode(_ data: Data) throws -> Catalog {
    try JSONDecoder().decode(Catalog.self, from: data)
  }

  /// Human label for a `kind`. Unknown kinds pass through rather than being
  /// mapped to "Other": a new ecosystem in the generator should be visible
  /// here, not swallowed.
  public static func sectionTitle(for kind: String) -> String {
    switch kind {
    case "npm": return "Application"
    case "cargo": return "Engine"
    case "bundled": return "Bundled"
    default: return kind
    }
  }

  /// Group into sections for display, in a fixed order so the list does not
  /// reshuffle between two reads of the same data, with each section's
  /// components sorted case-insensitively by name.
  public static func sections(of components: [Component]) -> [Section] {
    let order = ["bundled", "npm", "cargo"]
    var byKind: [String: [Component]] = [:]
    for component in components {
      byKind[component.kind, default: []].append(component)
    }
    let known = order.filter { byKind[$0] != nil }
    let unknown = byKind.keys.filter { !order.contains($0) }.sorted()
    return (known + unknown).map { kind in
      Section(
        title: sectionTitle(for: kind),
        components: (byKind[kind] ?? []).sorted {
          let byName = $0.name.localizedCaseInsensitiveCompare($1.name)
          if byName != .orderedSame { return byName == .orderedAscending }
          // Two builds of one package: keep the ordering total so it cannot
          // depend on the order the generator happened to emit.
          return ($0.version ?? "") < ($1.version ?? "")
        })
    }
  }

  /// Filter by a search string, matched against the package name, its licence
  /// and its publisher — the three things someone looking for a specific
  /// obligation would type. Empty or whitespace-only query returns everything.
  public static func filter(_ components: [Component], query: String) -> [Component] {
    let needle = query.trimmingCharacters(in: .whitespacesAndNewlines)
    guard !needle.isEmpty else { return components }
    return components.filter { component in
      component.name.localizedCaseInsensitiveContains(needle)
        || (component.license?.localizedCaseInsensitiveContains(needle) ?? false)
        || (component.publisher?.localizedCaseInsensitiveContains(needle) ?? false)
    }
  }

  /// Components the generator could not find a licence text for.
  ///
  /// The packaging guard: `scripts/check-license-catalog.sh` asserts this stays
  /// within what the generator itself reports, so a change that silently drops
  /// notices from the bundle fails rather than shipping.
  public static func componentsWithoutText(_ catalog: Catalog) -> [Component] {
    catalog.components.filter { catalog.text(for: $0) == nil }
  }

  /// Subtitle for a row: the licence, and the version when there is one.
  public static func subtitle(for component: Component) -> String {
    let licence = component.license ?? "Licence not declared"
    guard let version = component.version, !version.isEmpty else { return licence }
    return "\(licence) · \(version)"
  }
}
