#!/usr/bin/env python3
"""Generate .claude/feedback/INDEX.md from the YAML frontmatter of each
feedback_*.md file. Re-run after any rule add/edit to keep the index current.

Output sections:
- Skill → rules (most useful for AW agents looking up "what applies to me")
- All rules (sorted alphabetically, with bucket + description)
"""
import re
import sys
from pathlib import Path

FEEDBACK_DIR = Path(".claude/feedback")
OUT = FEEDBACK_DIR / "INDEX.md"


def parse_frontmatter(text: str) -> dict:
    """Cheap YAML frontmatter parser — only handles the fields we use."""
    m = re.match(r"^---\n(.*?)\n---\n", text, re.DOTALL)
    if not m:
        return {}
    body = m.group(1)
    out = {}
    for line in body.split("\n"):
        if ":" not in line:
            continue
        key, _, val = line.partition(":")
        key = key.strip()
        val = val.strip()
        if val.startswith("[") and val.endswith("]"):
            val = [v.strip() for v in val[1:-1].split(",") if v.strip()]
        elif val.startswith('"') and val.endswith('"'):
            val = val[1:-1].replace('\\"', '"')
        out[key] = val
    return out


def main():
    files = sorted(FEEDBACK_DIR.glob("feedback_*.md"))
    if len(files) != 41:
        print(f"warn: expected 41 files, found {len(files)}", file=sys.stderr)

    rules = []
    for f in files:
        fm = parse_frontmatter(f.read_text(encoding="utf-8"))
        rules.append({
            "file": f.name,
            "stem": f.stem,
            "name": fm.get("name", f.stem),
            "description": fm.get("description", "").strip('"'),
            "aw_applies": fm.get("aw_applies", "no"),
            "aw_applies_to": fm.get("aw_applies_to", []) if isinstance(fm.get("aw_applies_to"), list) else [],
            "aw_note": fm.get("aw_note", ""),
        })

    # By skill
    skill_to_rules: dict[str, list[str]] = {}
    for r in rules:
        if r["aw_applies"] == "no":
            continue
        for skill in r["aw_applies_to"]:
            skill_to_rules.setdefault(skill, []).append(r["file"])

    # Output
    lines = [
        "<!-- AUTO-GENERATED by scripts/gen-feedback-index.py. Do not hand-edit. -->",
        "# Feedback rule index",
        "",
        "Generated from the `aw_applies` / `aw_applies_to` frontmatter of every",
        "`feedback_*.md` in this directory. AW skills read this file plus every rule",
        "whose `aw_applies` is `yes` or `with-modification` as their Step 0.",
        "",
        "## By skill",
        "",
        "Each AW skill should load AT LEAST the rules in its row below. `all` means",
        "every skill loads the rule regardless of skill identity.",
        "",
    ]

    # Stable skill order
    skill_order = ["all", "aw-triage", "aw-refine", "aw-slice", "aw-tdd", "aw-review", "aw-iterate", "aw-ci-repair", "aw-retrospect", "aw-feedback"]
    for skill in skill_order:
        if skill not in skill_to_rules:
            continue
        lines.append(f"### {skill}")
        lines.append("")
        for rf in sorted(skill_to_rules[skill]):
            r = next(rr for rr in rules if rr["file"] == rf)
            lines.append(f"- [{r['file']}]({r['file']}) — {r['description']}")
        lines.append("")

    # Counts table
    counts = {"yes": 0, "with-modification": 0, "no": 0}
    for r in rules:
        counts[r["aw_applies"]] = counts.get(r["aw_applies"], 0) + 1
    lines += [
        "## Bucket counts",
        "",
        "| Bucket | Count | Loaded by AW skills? |",
        "|---|---|---|",
        f"| `yes` | {counts['yes']} | Yes — every skill that lists the rule in its `aw_applies_to` |",
        f"| `with-modification` | {counts['with-modification']} | Yes — with the modification noted in the rule's `aw_note` |",
        f"| `no` | {counts['no']} | No — interactive-only or out of AW scope |",
        f"| **Total** | **{sum(counts.values())}** | |",
        "",
    ]

    # All rules table
    lines += [
        "## All rules (alphabetical)",
        "",
        "| File | Bucket | Skills | Description |",
        "|---|---|---|---|",
    ]
    for r in sorted(rules, key=lambda x: x["file"]):
        skills = ", ".join(r["aw_applies_to"]) if r["aw_applies_to"] else "—"
        desc = r["description"].replace("|", "\\|")
        lines.append(f"| [{r['file']}]({r['file']}) | `{r['aw_applies']}` | {skills} | {desc} |")
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT} ({sum(counts.values())} rules indexed)")


if __name__ == "__main__":
    main()
