#!/usr/bin/env python3
"""Generate .claude/feedback/INDEX.md from the YAML frontmatter of each
feedback_*.md file AND inject the per-skill "Most-relevant feedback rules"
section into every aw-*/SKILL.md. Re-run after any rule add/edit to keep
both surfaces in sync.

Output:
- .claude/feedback/INDEX.md
  - Skill → rules (most useful for AW agents looking up "what applies to me")
  - All rules (sorted alphabetically, with bucket + description)
- .claude/skills/aw-*/SKILL.md
  - "## Most-relevant feedback rules for this skill" section at the end,
    bounded by `<!-- BEGIN/END auto-generated by gen-feedback-index.py -->`
    markers. Inserts the section the first time, replaces between markers
    on subsequent runs.
"""
import re
import sys
from pathlib import Path

FEEDBACK_DIR = Path(".claude/feedback")
OUT = FEEDBACK_DIR / "INDEX.md"
SKILLS_DIR = Path(".claude/skills")
SKILLS = [
    "aw-triage", "aw-refine", "aw-slice", "aw-tdd", "aw-review",
    "aw-iterate", "aw-ci-repair", "aw-retrospect", "aw-feedback",
]

INJECT_BEGIN = "<!-- BEGIN auto-generated by scripts/gen-feedback-index.py — do not hand-edit -->"
INJECT_END = "<!-- END auto-generated -->"


def parse_frontmatter(text: str) -> dict:
    """Cheap YAML frontmatter parser — only handles the fields we use."""
    m = re.match(r"^---\n(.*?)\n---\n", text, re.DOTALL)
    if not m:
        return {}
    body = m.group(1)
    out = {}
    for line in body.split("\n"):
        if ":" not in line:
            continue
        key, _, val = line.partition(":")
        key = key.strip()
        val = val.strip()
        if val.startswith("[") and val.endswith("]"):
            val = [v.strip() for v in val[1:-1].split(",") if v.strip()]
        elif val.startswith('"') and val.endswith('"'):
            val = val[1:-1].replace('\\"', '"')
        out[key] = val
    return out


def main():
    files = sorted(FEEDBACK_DIR.glob("feedback_*.md"))
    if not files:
        print("error: no feedback_*.md files found in .claude/feedback/", file=sys.stderr)
        sys.exit(1)

    rules = []
    for f in files:
        fm = parse_frontmatter(f.read_text(encoding="utf-8"))
        rules.append({
            "file": f.name,
            "stem": f.stem,
            "name": fm.get("name", f.stem),
            "description": fm.get("description", "").strip('"'),
            "aw_applies": fm.get("aw_applies", "no"),
            "aw_applies_to": fm.get("aw_applies_to", []) if isinstance(fm.get("aw_applies_to"), list) else [],
            "aw_note": fm.get("aw_note", ""),
        })

    # By skill
    skill_to_rules: dict[str, list[str]] = {}
    for r in rules:
        if r["aw_applies"] == "no":
            continue
        for skill in r["aw_applies_to"]:
            skill_to_rules.setdefault(skill, []).append(r["file"])

    # Output
    lines = [
        "<!-- AUTO-GENERATED by scripts/gen-feedback-index.py. Do not hand-edit. -->",
        "# Feedback rule index",
        "",
        "Generated from the `aw_applies` / `aw_applies_to` frontmatter of every",
        "`feedback_*.md` in this directory. AW skills read this file plus every rule",
        "whose `aw_applies` is `yes` or `with-modification` as their Step 0.",
        "",
        "## By skill",
        "",
        "Each AW skill should load AT LEAST the rules in its row below. `all` means",
        "every skill loads the rule regardless of skill identity.",
        "",
    ]

    # Stable skill order
    skill_order = ["all", "aw-triage", "aw-refine", "aw-slice", "aw-tdd", "aw-review", "aw-iterate", "aw-ci-repair", "aw-retrospect", "aw-feedback"]
    for skill in skill_order:
        if skill not in skill_to_rules:
            continue
        lines.append(f"### {skill}")
        lines.append("")
        for rf in sorted(skill_to_rules[skill]):
            r = next(rr for rr in rules if rr["file"] == rf)
            lines.append(f"- [{r['file']}]({r['file']}) — {r['description']}")
        lines.append("")

    # Counts table
    counts = {"yes": 0, "with-modification": 0, "no": 0}
    for r in rules:
        counts[r["aw_applies"]] = counts.get(r["aw_applies"], 0) + 1
    lines += [
        "## Bucket counts",
        "",
        "| Bucket | Count | Loaded by AW skills? |",
        "|---|---|---|",
        f"| `yes` | {counts['yes']} | Yes — every skill that lists the rule in its `aw_applies_to` |",
        f"| `with-modification` | {counts['with-modification']} | Yes — with the modification noted in the rule's `aw_note` |",
        f"| `no` | {counts['no']} | No — interactive-only or out of AW scope |",
        f"| **Total** | **{sum(counts.values())}** | |",
        "",
    ]

    # All rules table
    lines += [
        "## All rules (alphabetical)",
        "",
        "| File | Bucket | Skills | Description |",
        "|---|---|---|---|",
    ]
    for r in sorted(rules, key=lambda x: x["file"]):
        skills = ", ".join(r["aw_applies_to"]) if r["aw_applies_to"] else "—"
        desc = r["description"].replace("|", "\\|")
        lines.append(f"| [{r['file']}]({r['file']}) | `{r['aw_applies']}` | {skills} | {desc} |")
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT} ({sum(counts.values())} rules indexed)")

    inject_into_skills(rules, skill_to_rules)


def build_skill_section(skill: str, rules: list[dict], skill_to_rules: dict) -> str:
    """Build the 'Most-relevant feedback rules for this skill' section body."""
    own = sorted(skill_to_rules.get(skill, []))
    universal = sorted(skill_to_rules.get("all", []))

    lines = [
        "## Most-relevant feedback rules for this skill",
        "",
        "When context budget is tight, prioritise loading these rules from",
        "`.claude/feedback/` (the full set is in `.claude/feedback/INDEX.md`).",
        "",
        INJECT_BEGIN,
        "",
    ]

    if universal:
        lines.append("**Universal (load for every skill):**")
        lines.append("")
        for rf in universal:
            r = next(rr for rr in rules if rr["file"] == rf)
            lines.append(f"- `.claude/feedback/{rf}` — {r['description']}")
        lines.append("")

    if own:
        lines.append(f"**Specific to `{skill}`:**")
        lines.append("")
        for rf in own:
            r = next(rr for rr in rules if rr["file"] == rf)
            note = ""
            if r.get("aw_note"):
                note = f" *(modification: {r['aw_note']})*"
            lines.append(f"- `.claude/feedback/{rf}` — {r['description']}{note}")
        lines.append("")
    elif not universal:
        lines.append(f"*(No rules currently target `{skill}`. If a feedback rule's behaviour applies here, add `{skill}` to its `aw_applies_to` frontmatter.)*")
        lines.append("")

    lines.append(INJECT_END)
    return "\n".join(lines)


def inject_into_skills(rules: list[dict], skill_to_rules: dict) -> None:
    """Insert or replace the per-skill curated section in each aw-*/SKILL.md.

    First-run behaviour: appends the section at the end of the file (preceded
    by a blank line). Re-run behaviour: locates the BEGIN/END markers and
    replaces the content between them, preserving any surrounding text.
    """
    inject_count = 0
    update_count = 0
    for slug in SKILLS:
        f = SKILLS_DIR / slug / "SKILL.md"
        if not f.exists():
            print(f"  warn: {f} not found, skipping injection", file=sys.stderr)
            continue

        content = f.read_text(encoding="utf-8")
        section = build_skill_section(slug, rules, skill_to_rules)

        if INJECT_BEGIN in content and INJECT_END in content:
            # Replace content between markers (preserving the wrapping section header).
            # We replace the full "## Most-relevant feedback rules" section to be
            # safe — locate the section header and everything down to INJECT_END.
            pattern = re.compile(
                r"## Most-relevant feedback rules for this skill\n.*?" + re.escape(INJECT_END),
                re.DOTALL,
            )
            new_content = pattern.sub(section, content)
            if new_content == content:
                # Markers exist but section header missing — unusual; just no-op.
                continue
            if new_content != content:
                f.write_text(new_content, encoding="utf-8")
                update_count += 1
                print(f"  updated {slug}")
        else:
            # Append at end with a separating blank line.
            sep = "" if content.endswith("\n\n") else ("\n" if content.endswith("\n") else "\n\n")
            new_content = content + sep + section + "\n"
            f.write_text(new_content, encoding="utf-8")
            inject_count += 1
            print(f"  inserted into {slug}")

    print(f"\nSkill injection: {inject_count} inserted, {update_count} updated.")


if __name__ == "__main__":
    main()
