#!/usr/bin/env bash
# Integrate the committed iOS native sources into the generated Xcode project.
#
# `src-tauri/gen/` is gitignored and regenerated by `tauri ios init`, so the
# Swift lives here (committed) and is copied in. Run this after any
# `tauri ios init`, and after editing anything under src-tauri/ios/.
#
#   src-tauri/ios/sync-native.sh
#
# What it does:
#   1. copies the app-target Swift + bridging header into gen/apple/Sources
#   2. builds the notesage-capture staticlib for the requested target
#   3. patches project.yml with the bridging header + link settings
#   4. re-runs xcodegen so the .xcodeproj picks all of it up
#
# ShareViewController.swift is deliberately NOT copied: it belongs to a Share
# Extension target, which `tauri ios init` does not create. Adding that target
# is still a manual Xcode step (see README).
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
TAURI_DIR="$(cd "$HERE/.." && pwd)"
GEN="$TAURI_DIR/gen/apple"
DEST="$GEN/Sources/notesage"

# `sim` (default) or `device`.
VARIANT="${1:-sim}"
case "$VARIANT" in
  sim)    RUST_TARGET="aarch64-apple-ios-sim" ;;
  device) RUST_TARGET="aarch64-apple-ios" ;;
  *) echo "usage: $0 [sim|device]" >&2; exit 1 ;;
esac

[ -d "$GEN" ] || { echo "ERROR: $GEN not found — run \`pnpm tauri:ios:init\` first." >&2; exit 1; }

echo "== copying native sources"
mkdir -p "$DEST"
cp "$HERE/LibraryAccess.swift" "$HERE/NotesagePlugin.swift" "$HERE/NotesageCapture.h" "$DEST/"

echo "== building notesage-capture ($RUST_TARGET)"
cargo build --release --target "$RUST_TARGET" \
  --manifest-path "$TAURI_DIR/crates/notesage-capture/Cargo.toml"

LIB_DIR="$TAURI_DIR/target/$RUST_TARGET/release"
[ -f "$LIB_DIR/libnotesage_capture.a" ] || { echo "ERROR: staticlib not built" >&2; exit 1; }

# The Tauri iOS Swift API (`import Tauri`) is only added to the generated
# project when a plugin ships iOS Swift. Notesage has none, so NotesagePlugin
# would fail to compile and its `@_cdecl("init_plugin_notesage")` symbol would
# be missing at link — surfacing as an opaque "symbol(s) not found" against the
# Rust object, not as a Swift error. Resolve the package from the tauri crate
# actually in use so it can never drift from the Rust side.
TAURI_VER="$(cargo metadata --format-version 1 --manifest-path "$TAURI_DIR/Cargo.toml" --no-deps 2>/dev/null >/dev/null; \
  cargo tree -p tauri --depth 0 --manifest-path "$TAURI_DIR/Cargo.toml" 2>/dev/null | head -1 | sed -E 's/^tauri v([0-9.]+).*/\1/')"
IOS_API="$(ls -d "$HOME"/.cargo/registry/src/index.crates.io-*/tauri-"$TAURI_VER"/mobile/ios-api 2>/dev/null | head -1)"
[ -n "$IOS_API" ] || { echo "ERROR: could not find the Tauri iOS Swift package for tauri $TAURI_VER" >&2; exit 1; }
echo "== Tauri iOS Swift API: $IOS_API"

echo "== patching project.yml"
python3 - "$GEN/project.yml" "$LIB_DIR" "$IOS_API" <<'PY'
import sys
path, lib_dir, ios_api = sys.argv[1], sys.argv[2], sys.argv[3]
src = open(path).read()

# The bridging header lets Swift see the capture C ABI; the search path + flag
# link the staticlib that implements it. Anchored on the app target's own
# `entitlements:` key so we patch that target and not the template.
# MERGE into the target's existing `settings.base` — adding a second
# `settings:` key would be silently discarded, because a later duplicate key
# wins in YAML and the generated block comes after ours.
anchor = "        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: true"
if "SWIFT_OBJC_BRIDGING_HEADER" in src:
    print("   already patched")
else:
    if anchor not in src:
        sys.exit("ERROR: could not find the app target's settings anchor in project.yml")
    block = (
        anchor + "\n"
        "        SWIFT_OBJC_BRIDGING_HEADER: Sources/notesage/NotesageCapture.h\n"
        f"        LIBRARY_SEARCH_PATHS[sdk=iphonesimulator*]: $(inherited) {lib_dir}\n"
        f"        LIBRARY_SEARCH_PATHS[sdk=iphoneos*]: $(inherited) {lib_dir}\n"
        "        OTHER_LDFLAGS: $(inherited) -lnotesage_capture"
    )
    src = src.replace(anchor, block, 1)
    open(path, "w").write(src)
    print("   merged bridging header + link settings into the target")

# `tauri ios init` writes deploymentTarget 14.0 and does not re-read
# tauri.conf.json on later builds, so the iOS overlay's minimumSystemVersion is
# not enough on its own. 16.0 is what the PRD specifies, and NotesagePlugin
# needs >= 15 for `UIWindowScene.keyWindow`.
src = open(path).read()
if "iOS: 14.0" in src:
    src = src.replace("iOS: 14.0", "iOS: 16.0")
    open(path, "w").write(src)
    print("   raised deploymentTarget to iOS 16.0")

src = open(path).read()
if "packages:" in src and "Tauri:" in src:
    print("   Tauri Swift package already referenced")
else:
    # Top-level `packages:` block + a target dependency on it.
    src = src.replace("targets:\n", f"packages:\n  Tauri:\n    path: {ios_api}\ntargets:\n", 1)
    dep_anchor = "    dependencies:\n      - framework: libapp.a"
    if dep_anchor not in src:
        sys.exit("ERROR: could not find the app target's dependencies anchor")
    src = src.replace(dep_anchor,
                      "    dependencies:\n      - package: Tauri\n      - framework: libapp.a", 1)
    open(path, "w").write(src)
    print("   added the Tauri Swift package dependency")
PY

echo "== regenerating the Xcode project"
( cd "$GEN" && xcodegen generate --quiet )

echo "Done. Native sources are in the app target."
