import { useEffect, useMemo, useState } from "react";
import { ChevronDown, Search } from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { ScrollArea } from "@/components/ui/scroll-area";
import { cn } from "@/lib/utils";
import { t } from "@/lib/i18n";

/** The shape `scripts/generate-licenses.mjs` writes. */
interface LicenseComponent {
  kind: "bundled" | "npm" | "cargo";
  name: string;
  version: string;
  license: string;
  publisher: string | null;
  url: string | null;
  /** Key into `texts`; null when the package shipped no licence file. */
  textId: string | null;
}

interface LicenseData {
  components: LicenseComponent[];
  texts: Record<string, string>;
}

/** Group order — bundled first, because those are the pieces a reader is most
 *  likely to have heard of. Headings are resolved at render, not here: a
 *  module-scope `t()` would freeze the labels at whatever locale was current
 *  when this module first loaded. */
const GROUP_ORDER: LicenseComponent["kind"][] = ["bundled", "npm", "cargo"];

const GROUP_LABEL: Record<LicenseComponent["kind"], () => string> = {
  bundled: () => t("licenses.groupBundled"),
  npm: () => t("licenses.groupNpm"),
  cargo: () => t("licenses.groupCargo"),
};

function ComponentRow({
  component,
  text,
  expanded,
  onToggle,
}: {
  component: LicenseComponent;
  text: string | null;
  expanded: boolean;
  onToggle: () => void;
}) {
  return (
    <div className="border border-border rounded-lg overflow-hidden">
      <button
        type="button"
        onClick={onToggle}
        aria-expanded={expanded}
        className="w-full flex items-center gap-3 px-3 py-2 text-left hover:bg-accent/50 transition-colors duration-150"
      >
        <div className="min-w-0 flex-1">
          <div className="flex items-baseline gap-2">
            <span className="text-sm font-medium truncate">{component.name}</span>
            <span className="text-xs text-muted-foreground tabular-nums shrink-0">{component.version}</span>
          </div>
          <p className="text-xs text-muted-foreground mt-0.5 truncate">
            {component.license}
            {component.publisher ? ` · ${component.publisher}` : ""}
          </p>
        </div>
        <ChevronDown
          className={cn(
            "h-4 w-4 shrink-0 text-muted-foreground transition-transform duration-150",
            expanded && "rotate-180",
          )}
          strokeWidth={1.5}
        />
      </button>
      {expanded && (
        <div className="border-t border-border px-3 py-3 space-y-2">
          {component.url && <p className="text-xs text-muted-foreground break-all">{component.url}</p>}
          {text ? (
            <pre className="text-[11px] leading-relaxed text-muted-foreground whitespace-pre-wrap font-mono">
              {text}
            </pre>
          ) : (
            <p className="text-xs text-muted-foreground">
              {t("licenses.noText")} {component.license}
            </p>
          )}
        </div>
      )}
    </div>
  );
}

/**
 * Every third-party component that ships inside Notesage, with its licence
 * text (#949).
 *
 * The list is generated by `scripts/generate-licenses.mjs` from the npm and
 * cargo manifests, so it cannot drift from what is actually bundled. It is
 * loaded on FIRST OPEN rather than imported at module scope: it is ~1.7 MB of
 * notice text, which has no business in the startup bundle for a dialog most
 * people never open. Once loaded it is held for the session.
 *
 * Deliberately offline — the texts are in the app, not fetched — because the
 * obligation is to ship the notice, not to link to it.
 */
export function LicensesDialog({
  open,
  onOpenChange,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}) {
  const [data, setData] = useState<LicenseData | null>(null);
  const [failed, setFailed] = useState(false);
  const [query, setQuery] = useState("");
  const [expanded, setExpanded] = useState<string | null>(null);

  useEffect(() => {
    if (!open || data || failed) return;
    let cancelled = false;
    void import("@/generated/third-party-licenses.json")
      .then((m) => {
        if (!cancelled) setData((m.default ?? m) as unknown as LicenseData);
      })
      .catch(() => {
        if (!cancelled) setFailed(true);
      });
    return () => {
      cancelled = true;
    };
  }, [open, data, failed]);

  const groups = useMemo(() => {
    if (!data) return [];
    const needle = query.trim().toLowerCase();
    const match = (c: LicenseComponent) =>
      !needle ||
      c.name.toLowerCase().includes(needle) ||
      c.license.toLowerCase().includes(needle) ||
      (c.publisher?.toLowerCase().includes(needle) ?? false);
    return GROUP_ORDER.map((kind) => ({
      kind,
      label: GROUP_LABEL[kind](),
      items: data.components.filter((c) => c.kind === kind && match(c)),
    })).filter((g) => g.items.length > 0);
  }, [data, query]);

  const total = data?.components.length ?? 0;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="w-[864px] sm:max-w-[864px] h-[min(720px,calc(100vh-48px))] p-0 gap-0 overflow-hidden flex flex-col">
        <DialogHeader className="px-7 pt-7 pb-3 border-b border-border shrink-0">
          <DialogTitle className="text-[20px] font-semibold tracking-tight">
            {t("licenses.title")}
          </DialogTitle>
          <DialogDescription className="mt-1 text-[13px] text-muted-foreground leading-relaxed">
            {total > 0 ? t("licenses.subtitleCount", { count: String(total) }) : t("licenses.subtitle")}
          </DialogDescription>
          <div className="relative mt-3">
            <Search
              className="pointer-events-none absolute left-2.5 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-muted-foreground"
              strokeWidth={1.5}
            />
            <Input
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              placeholder={t("licenses.searchPlaceholder")}
              aria-label={t("licenses.searchPlaceholder")}
              className="pl-8 h-8 text-sm"
            />
          </div>
        </DialogHeader>

        <div className="flex-1 min-h-0">
          <ScrollArea className="h-full">
            <div className="px-7 py-5 space-y-5">
              {failed && (
                <p className="text-sm text-muted-foreground text-center py-8">{t("licenses.failed")}</p>
              )}
              {!failed && !data && (
                <p className="text-sm text-muted-foreground text-center py-8">{t("licenses.loading")}</p>
              )}
              {data && groups.length === 0 && (
                <p className="text-sm text-muted-foreground text-center py-8">{t("licenses.noMatches")}</p>
              )}
              {groups.map((group) => (
                <div key={group.kind} className="space-y-2">
                  <h3 className="text-xs font-medium uppercase tracking-wider text-muted-foreground">
                    {group.label}
                  </h3>
                  <div className="space-y-1.5">
                    {group.items.map((c) => {
                      const key = `${c.kind}:${c.name}@${c.version}`;
                      return (
                        <ComponentRow
                          key={key}
                          component={c}
                          text={c.textId ? (data?.texts[c.textId] ?? null) : null}
                          expanded={expanded === key}
                          onToggle={() => setExpanded(expanded === key ? null : key)}
                        />
                      );
                    })}
                  </div>
                </div>
              ))}
            </div>
          </ScrollArea>
        </div>
      </DialogContent>
    </Dialog>
  );
}
